default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PROC_CONSUL_DB_HOST'] %>
  port: <%= ENV['PROC_CONSUL_DB_PORT'] %>
  pool: <%= ENV['PROC_CONSUL_DB_POOL_SIZE'] %>
  username: <%= ENV['PROC_CONSUL_DB_USER'] %>
  password: <%= ENV['PROC_CONSUL_DB_PASS'] %>
  database: <%= ENV['PROC_CONSUL_DB_NAME'] %>

development: &development
  <<: *default
  database: consul_development

staging:
  <<: *default

preproduction:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: consul_test
